### ISSUE TITLE
Create Firefox version

### ISSUE THREAD

**Issue by jcserracampos** [slavingia/darkdocs#8]
I know that everyone loves Chrome, but I prefer Firefox.

Can we have a Firefox version?

(I will try to port... someday)

**Comment by slavingia** [comment]
why tho? jk, yes!

**Comment by JS-goose** [comment]
I'm definitely on that Firefox train and would love to see a version of this for FF 😺

**Comment by slavingia** [comment]
It's now done for FF. Submitted to their add-on distro.
